# Specify a command to be executed
# like `/bin/bash -l`, `ls`, or any other commands
# the default is bash for Linux
# or powershell.exe for Windows
command: zsh

# Specify the current working directory path
# the default is the current working directory path
cwd: null

# Export additional ENV variables
env:
  recording: true

# Explicitly set the number of columns
# or use `auto` to take the current
# number of columns of your shell
cols: auto

# Explicitly set the number of rows
# or use `auto` to take the current
# number of rows of your shell
rows: auto

# Amount of times to repeat GIF
# If value is -1, play once
# If value is 0, loop indefinitely
# If value is a positive number, loop n times
repeat: 0

# Quality
# 1 - 100
quality: 100

# Delay between frames in ms
# If the value is `auto` use the actual recording delays
frameDelay: auto

# Maximum delay between frames in ms
# Ignored if the `frameDelay` isn't set to `auto`
# Set to `auto` to prevent limiting the max idle time
maxIdleTime: 2000

# The surrounding frame box
# The `type` can be null, window, floating, or solid`
# To hide the title use the value null
# Don't forget to add a backgroundColor style with a null as type
frameBox:
  type: solid
  title: null
  style: []
    # border: 0px black solid
    # boxShadow: none
    # margin: 0px

# Add a watermark image to the rendered gif
# You need to specify an absolute path for
# the image on your machine or a URL, and you can also
# add your own CSS styles
watermark:
  imagePath: null
  style:
    position: absolute
    right: 15px
    bottom: 15px
    width: 100px
    opacity: 0.9

# Cursor style can be one of
# `block`, `underline`, or `bar`
cursorStyle: block

# Font family
# You can use any font that is installed on your machine
# in CSS-like syntax
fontFamily: "DejaVu LGC Sans Mono, DejaVu Sans Mono, Droid Noto Mono"

# The size of the font
fontSize: 14

# The height of lines
lineHeight: 1.2

# The spacing between letters
letterSpacing: 0

# Theme
theme:
  background: "#282828"
  foreground: "#ebdbb2"
  cursor: "#ebdbb2"
  black: "#282828"
  red: "#cc241d"
  green: "#98971a"
  yellow: "#d79921"
  blue: "#458588"
  magenta: "#b16286"
  cyan: "#689d6a"
  white: "#ebdbb2"
  brightBlack: "#1d2021"
  brightRed: "#fb4934"
  brightGreen: "#b8bb26"
  brightYellow: "#fabd2f"
  brightBlue: "#83a598"
  brightMagenta: "#d3869b"
  brightCyan: "#8ec07c"
  brightWhite: "#fbf1c7"
