steps:
  - records:
      equals: "indent 2"
      first_field: "indent 2"
      field_comment: 2
      deriving: 2
  - imports:
      align: group
      list_align: with_module_name
      pad_module_names: false
      long_list_align: new_line_multiline
      empty_list_align: right_after
      list_padding: module_name # 7 "import " # def 4
      separate_lists: true
      space_surround: false
  - language_pragmas:
      style: vertical
      align: false
      remove_redundant: true
  - simple_align:
      cases: true #testing
      top_level_patterns: true #testing
      records: true #testing
  - trailing_whitespace: {}

language_extensions:
  - BlockArguments
  - DeriveFunctor
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiWayIf
  - NamedFieldPuns
  - MultiParamTypeClasses
  - OverloadedStrings
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections

columns: 80
cabal: true
indent: 2
